from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

import matplotlib.pyplot as plt
import numpy as np
import cv2


def segment_tumor(ct_image):

    img = ct_image.astype(np.float32)

    img = (img - np.min(img)) / (np.max(img) - np.min(img))

    img = (img * 255).astype(np.uint8)

    # Simple threshold segmentation
    _, thresh = cv2.threshold(img, 120, 255, cv2.THRESH_BINARY)

    kernel = np.ones((5,5),np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    return thresh


def generate_report(result, ct_image, filename="prediction_report.pdf"):

    styles = getSampleStyleSheet()

    risk_map = {
        0: "Low Aggressiveness",
        1: "Moderate Aggressiveness",
        2: "High Aggressiveness"
    }

    risk = risk_map[result["fusion_prediction"]]

    # ---------- SEGMENTATION ----------
    mask = segment_tumor(ct_image)

    overlay = cv2.cvtColor(ct_image.astype(np.uint8), cv2.COLOR_GRAY2BGR)
    overlay[mask > 0] = [255,0,0]   # tumor highlight

    # Save visualization
    fig_path = "ct_segmented.png"

    plt.figure(figsize=(5,5))
    plt.imshow(overlay)
    plt.title("CT Tumor Segmentation")
    plt.axis("off")
    plt.savefig(fig_path, bbox_inches="tight")
    plt.close()

    # ---------- REPORT ----------
    elements = []

    elements.append(Paragraph("AI Lung Tumor Aggressiveness Report", styles['Title']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph("Model: RadGenXGBoost (Radiomics + Genomics Fusion)", styles['Normal']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"<b>Predicted Risk Level:</b> {risk}", styles['Heading2']))
    elements.append(Spacer(1,15))

    explanation = ""

    if risk == "Low Aggressiveness":
        explanation = "The tumor shows low aggressive characteristics. Growth rate is expected to be slow and prognosis is generally favorable."

    elif risk == "Moderate Aggressiveness":
        explanation = "The tumor shows moderate aggressive characteristics. Further clinical monitoring is recommended."

    else:
        explanation = "The tumor appears highly aggressive. Immediate medical evaluation and treatment planning are recommended."

    elements.append(Paragraph(explanation, styles['Normal']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph("CT Tumor Visualization", styles['Heading3']))
    elements.append(Image(fig_path, width=4*inch, height=4*inch))
    elements.append(Spacer(1,20))

    elements.append(
        Paragraph(
            "Note: This report is generated by an AI-based clinical decision support system and should be reviewed by a qualified medical professional.",
            styles['Italic']
        )
    )

    doc = SimpleDocTemplate(filename)
    doc.build(elements)

    return filename